sudo: required

services:
    - docker

before_install:
    - docker build -t ryegoryshev/webclient-test -f ./WebClient/Dockerfile.dev ./WebClient/

script:
    - docker run ryegoryshev/webclient-test -e CI=true npm test 

after_success:
    - docker build -t ryegoryshev/multi-webclient ./WebClient/
    - docker build -t ryegoryshev/multi-api ./API/
    - docker build -t ryegoryshev/multi-nginx ./nginx/