version: '3'
services:
    web-client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./WebClient/
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./WebClient:/app
        environment: 
            - PORT=$WEB_CLIENT_INTERNAL_PORT
            - REACT_APP_API_HOST=$API_HOST
            - REACT_APP_API_PORT=$API_EXTERNAL_PORT
 #       ports:
 #           - $WEB_CLIENT_EXTERNAL_PORT:$WEB_CLIENT_INTERNAL_PORT
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./API/
 #       ports:
 #           - $API_EXTERNAL_PORT:$API_INTERNAL_PORT
        environment:
            - API_INTERNAL_PORT=$API_INTERNAL_PORT
            - PG_HOST=postgresql
            - PG_PORT=$PG_PORT
            - PG_USER=postgres
            - PG_PASSWORD=postgres_password
            - PG_DATABASE=postgres
        volumes: 
            - /app/node_modules
            - ./API:/app
        depends_on: 
            - postgresql
    postgresql:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    proxy:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - $PROXY_PORT:80
        depends_on: 
            - web-client
            - api
